export enum WorkOrderStatus {
  OPEN = "OPEN",
  PENDING = "PENDING",
  CANCELLED = "CANCELLED",
  COMPLETE = "COMPLETE",
  CLOSED = "CLOSED",
  ERROR = "ERROR",
  RETRY = "RETRY",
  PROCESSED = "PROCESSED"
}
